import ReactQueryProvider from '@/shared/providers/reactQueryProvider';
import StoreProvider from '@/shared/providers/reduxProvider';
import { ThemeProvider } from '@/shared/providers/themesProvider';
import Header from '@/widgets/Header';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import React from 'react';
import { Toaster } from 'sonner';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.variable} bg-lightSpace min-h-screen font-sans dark:bg-darkSpace`}
      >
        <StoreProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ReactQueryProvider>
              <div className={`grid grid-rows-[65px_4fr]`}>
                <Header />
                {children}
              </div>
              <Toaster richColors={true} />
            </ReactQueryProvider>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
