import { ProductCardInterface } from '@/shared/interfaces/productCard';

export const products: ProductCardInterface[] = [
  {
    productId: 0,
    productName: 'Cool Wireless Mouse',
    productHref: 'cool-wireless-mouse',
    productPrice: 55.99,
    productQuantity: 1,
    productDescription: 'A sleek wireless mouse with ergonomic design.',
  },
  {
    productId: 1,
    productName: 'Wireless Mouse',
    productHref: 'wireless-mouse',
    productPrice: 25.99,
    productQuantity: 1,
    productDescription: 'A sleek wireless mouse with ergonomic design.',
  },
  {
    productId: 2,
    productName: 'Bluetooth Keyboard',
    productHref: 'bluetooth-keyboard',
    productPrice: 45.5,
    productQuantity: 1,
    productDescription: 'A compact Bluetooth keyboard with quiet keys.',
  },
  {
    productId: 3,
    productName: 'Gaming Headset',
    productHref: 'gaming-headset',
    productPrice: 79.99,
    productQuantity: 1,
    productDescription: 'A high-quality gaming headset with surround sound.',
  },
  {
    productId: 4,
    productName: '4K Monitor',
    productHref: '4k-monitor',
    productPrice: 299.99,
    productQuantity: 1,
    productDescription:
      'A 27-inch 4K monitor with vibrant colors and sharp details.',
  },
  {
    productId: 5,
    productName: 'External Hard Drive',
    productHref: 'external-hard-drive',
    productPrice: 89.95,
    productQuantity: 1,
    productDescription:
      'A 1TB external hard drive with fast data transfer speeds.',
  },
  {
    productId: 6,
    productName: 'Smartphone Stand',
    productHref: 'smartphone-stand',
    productPrice: 12.99,
    productQuantity: 1,
    productDescription: 'A sturdy smartphone stand for desk or nightstand use.',
  },
  {
    productId: 7,
    productName: 'USB-C Hub',
    productHref: 'usb-c-hub',
    productPrice: 29.99,
    productQuantity: 1,
    productDescription:
      'A multi-port USB-C hub with HDMI, USB, and SD card slots.',
  },
  {
    productId: 8,
    productName: 'Portable Charger',
    productHref: 'portable-charger',
    productPrice: 34.99,
    productQuantity: 1,
    productDescription: 'A high-capacity portable charger with fast charging.',
  },
  {
    productId: 9,
    productName: 'Wireless Earbuds',
    productHref: 'wireless-earbuds',
    productPrice: 59.99,
    productQuantity: 1,
    productDescription:
      'Compact and comfortable wireless earbuds with excellent sound quality',
  },
  {
    productId: 10,
    productName: 'Fitness Tracker',
    productHref: 'fitness-tracker',
    productPrice: 49.99,
    productQuantity: 1,
    productDescription:
      'A fitness tracker with heart rate monitor and sleep tracking.',
  },
  {
    productId: 11,
    productName: 'Laptop Sleeve',
    productHref: 'laptop-sleeve',
    productPrice: 19.99,
    productQuantity: 1,
    productDescription: 'A protective laptop sleeve with a sleek design.',
  },
  {
    productId: 12,
    productName: 'Webcam',
    productHref: 'webcam',
    productPrice: 39.99,
    productQuantity: 1,
    productDescription: 'A high-definition webcam with built-in microphone',
  },
  {
    productId: 13,
    productName: 'Mechanical Keyboard',
    productHref: 'mechanical-keyboard',
    productPrice: 89.99,
    productQuantity: 1,
    productDescription: 'A mechanical keyboard with customizable RGB lighting.',
  },
  {
    productId: 14,
    productName: 'Smart Speaker',
    productHref: 'smart-speaker',
    productPrice: 69.99,
    productQuantity: 1,
    productDescription: 'A smart speaker with voice assistant integration.',
  },
  {
    productId: 15,
    productName: 'Action Camera',
    productHref: 'action-camera',
    productPrice: 119.99,
    productQuantity: 1,
    productDescription: 'A waterproof action camera with 4K video recording.',
  },
  {
    productId: 16,
    productName: 'Portable Bluetooth Speaker',
    productHref: 'portable-bluetooth-speaker',
    productPrice: 39.99,
    productQuantity: 1,
    productDescription: 'A compact Bluetooth speaker with rich sound quality.',
  },
  {
    productId: 17,
    productName: 'Wireless Charging Pad',
    productHref: 'wireless-charging-pad',
    productPrice: 29.99,
    productQuantity: 1,
    productDescription: 'A sleek wireless charging pad for smartphones.',
  },
  {
    productId: 18,
    productName: 'Cordless Vacuum Cleaner',
    productHref: 'cordless-vacuum-cleaner',
    productPrice: 149.99,
    productQuantity: 1,
    productDescription:
      'A lightweight cordless vacuum cleaner for quick cleaning.',
  },
  {
    productId: 19,
    productName: 'Coffee Maker',
    productHref: 'coffee-maker',
    productPrice: 79.99,
    productQuantity: 1,
    productDescription: 'A programmable coffee maker with a glass carafe.',
  },
  {
    productId: 20,
    productName: 'Gaming Mouse',
    productHref: 'gaming-mouse',
    productPrice: 49.99,
    productQuantity: 1,
    productDescription:
      'A high-precision gaming mouse with customizable buttons.',
  },
  {
    productId: 21,
    productName: 'Bluetooth Earphones',
    productHref: 'bluetooth-earphones',
    productPrice: 59.99,
    productQuantity: 1,
    productDescription: 'Wireless Bluetooth earphones with noise cancellation',
  },
  {
    productId: 22,
    productName: 'Robot Vacuum Cleaner',
    productHref: 'robot-vacuum-cleaner',
    productPrice: 299.99,
    productQuantity: 1,
    productDescription:
      'An intelligent robot vacuum cleaner for automated cleaning.',
  },
  {
    productId: 23,
    productName: 'Electric Toothbrush',
    productHref: 'electric-toothbrush',
    productPrice: 69.99,
    productQuantity: 1,
    productDescription:
      'A rechargeable electric toothbrush with multiple brushing modes.',
  },
  {
    productId: 24,
    productName: 'Air Purifier',
    productHref: 'air-purifier',
    productPrice: 129.99,
    productQuantity: 1,
    productDescription: 'A HEPA air purifier for cleaner indoor air quality.',
  },
  {
    productId: 25,
    productName: 'Wireless Router',
    productHref: 'wireless-router',
    productPrice: 89.99,
    productQuantity: 1,
    productDescription: 'A high-speed wireless router for home or office use.',
  },
  {
    productId: 26,
    productName: 'Digital Photo Frame',
    productHref: 'digital-photo-frame',
    productPrice: 79.99,
    productQuantity: 1,
    productDescription: 'A digital photo frame with a high-resolution display.',
  },
  {
    productId: 27,
    productName: 'Smart Thermostat',
    productHref: 'smart-thermostat',
    productPrice: 149.99,
    productQuantity: 1,
    productDescription:
      'A smart thermostat for energy-efficient temperature control.',
  },
  {
    productId: 28,
    productName: 'Portable Bluetooth Headphones',
    productHref: 'portable-bluetooth-headphones',
    productPrice: 99.99,
    productQuantity: 1,
    productDescription:
      'High-quality portable Bluetooth headphones with noise isolation.',
  },
  {
    productId: 29,
    productName: 'Desktop External SSD',
    productHref: 'desktop-external-ssd',
    productPrice: 179.99,
    productQuantity: 1,
    productDescription:
      'A high-speed desktop external SSD for fast data storage.',
  },
  {
    productId: 30,
    productName: 'Smart Doorbell',
    productHref: 'smart-doorbell',
    productPrice: 199.99,
    productQuantity: 1,
    productDescription: 'A smart doorbell with HD video and motion detection.',
  },
  {
    productId: 31,
    productName: 'Smart Scale',
    productHref: 'smart-scale',
    productPrice: 49.99,
    productQuantity: 1,
    productDescription: 'A smart scale with body composition analysis.',
  },
  {
    productId: 32,
    productName: 'Bluetooth Car Kit',
    productHref: 'bluetooth-car-kit',
    productPrice: 29.99,
    productQuantity: 1,
    productDescription:
      'A Bluetooth car kit for hands-free calling and music streaming.',
  },
  {
    productId: 33,
    productName: 'Wireless Desk Lamp',
    productHref: 'wireless-desk-lamp',
    productPrice: 39.99,
    productQuantity: 1,
    productDescription:
      'A modern wireless desk lamp with adjustable brightness.',
  },
  {
    productId: 34,
    productName: 'Electric Kettle',
    productHref: 'electric-kettle',
    productPrice: 34.99,
    productQuantity: 1,
    productDescription:
      'A fast-boiling electric kettle with a stainless steel finish.',
  },
  {
    productId: 35,
    productName: 'Wireless Charging Stand',
    productHref: 'wireless-charging-stand',
    productPrice: 24.99,
    productQuantity: 1,
    productDescription: 'A stylish wireless charging stand for smartphones.',
  },
  {
    productId: 36,
    productName: 'Bluetooth Tracker',
    productHref: 'bluetooth-tracker',
    productPrice: 19.99,
    productQuantity: 1,
    productDescription:
      'A Bluetooth tracker to find lost items like keys or bags.',
  },
  {
    productId: 37,
    productName: 'Mini Projector',
    productHref: 'mini-projector',
    productPrice: 129.99,
    productQuantity: 1,
    productDescription: 'A compact mini projector for home entertainment.',
  },
  {
    productId: 38,
    productName: 'Air Fryer',
    productHref: 'air-fryer',
    productPrice: 89.99,
    productQuantity: 1,
    productDescription: 'An air fryer for healthier cooking with less oil.',
  },
  {
    productId: 39,
    productName: 'Smart Plug',
    productHref: 'smart-plug',
    productPrice: 19.99,
    productQuantity: 1,
    productDescription: 'A smart plug for controlling appliances remotely.',
  },
  {
    productId: 40,
    productName: 'Digital Voice Recorder',
    productHref: 'digital-voice-recorder',
    productPrice: 59.99,
    productQuantity: 1,
    productDescription:
      'A digital voice recorder with long battery life and voice activation.',
  },
  {
    productId: 41,
    productName: 'Smart Watch Charger Stand',
    productHref: 'smart-watch-charger-stand',
    productPrice: 14.99,
    productQuantity: 1,
    productDescription:
      'A charging stand for smart watches with cable management.',
  },
  {
    productId: 42,
    productName: 'Wireless Gaming Controller',
    productHref: 'wireless-gaming-controller',
    productPrice: 69.99,
    productQuantity: 1,
    productDescription: 'A wireless gaming controller for PC and consoles.',
  },
  {
    productId: 43,
    productName: 'Portable Espresso Maker',
    productHref: 'portable-espresso-maker',
    productPrice: 79.99,
    productQuantity: 1,
    productDescription:
      'A portable espresso maker for coffee lovers on the go.',
  },
  {
    productId: 44,
    productName: 'Smart Ceiling Fan',
    productHref: 'smart-ceiling-fan',
    productPrice: 199.99,
    productQuantity: 1,
    productDescription:
      'A smart ceiling fan with remote and voice control features.',
  },
  {
    productId: 45,
    productName: 'Wireless Barcode Scanner',
    productHref: 'wireless-barcode-scanner',
    productPrice: 99.99,
    productQuantity: 1,
    productDescription:
      'A wireless barcode scanner for retail and inventory management.',
  },
  {
    productId: 46,
    productName: 'Electric Scooter',
    productHref: 'electric-scooter',
    productPrice: 299.99,
    productQuantity: 1,
    productDescription:
      'An electric scooter for urban commuting with foldable design.',
  },
  {
    productId: 47,
    productName: 'Smart Mirror',
    productHref: 'smart-mirror',
    productPrice: 249.99,
    productQuantity: 1,
    productDescription:
      'A smart mirror with built-in LED lights and weather updates.',
  },
  {
    productId: 48,
    productName: 'Portable Air Conditioner',
    productHref: 'portable-air-conditioner',
    productPrice: 349.99,
    productQuantity: 1,
    productDescription:
      'A portable air conditioner with remote control and timer settings.',
  },
  {
    productId: 49,
    productName: 'Smart Garden Kit',
    productHref: 'smart-garden-kit',
    productPrice: 79.99,
    productQuantity: 1,
    productDescription:
      'A smart garden kit for indoor herb and vegetable cultivation.',
  },
  {
    productId: 50,
    productName: 'Portable Blender',
    productHref: 'portable-blender',
    productPrice: 39.99,
    productQuantity: 1,
    productDescription:
      'A portable blender for making smoothies and shakes on the go.',
  },
];
